name: rcdnet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.7
  - pip
  - pip:
    - torch==1.13.1+cu117
    - torchvision==0.14.1+cu117
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - transformers==4.30.2
    - accelerate>=0.20.0
    - safetensors
    - huggingface-hub
    - timm>=0.9.0
    - opencv-python
    - pillow
    - einops
    - easydict
    - tqdm
    - matplotlib
    - scipy
    - wandb
    - ninja
    - PyYAML
    - git+https://github.com/openai/CLIP.git
